### ISSUE TITLE
Clang-Format Settings are different to used Coding Style

### ISSUE THREAD

**Issue by franneck94** [HasKha/GWToolboxpp#651]
Hi,

I wanted to start to implement some features. But before I wanted to format some code and there I saw that there is a mismatch in the clang-format file with the current *used* coding style.

In most of the codebase here the opening brace of a function is in the line of the parameters and not in a new line.
Regrading the clang-format file it should be on a new line.

```yaml
# Pretty much break after everything, but no braces indent.
# We are not savages afterall ;)
BreakBeforeBraces: Custom
BraceWrapping:
  AfterClass:            true
  AfterControlStatement: false
  AfterEnum:             true
  AfterFunction:         true
  AfterNamespace:        true
  AfterObjCDeclaration:  true
  AfterStruct:           true
  AfterUnion:            true
  AfterExternBlock:      true
  AfterCaseLabel:        false
  BeforeCatch:           false
  BeforeElse:            false
  IndentBraces:          false
  SplitEmptyFunction:    true
  SplitEmptyRecord:      true
  SplitEmptyNamespace:   true
```

![Screenshot_2](https://user-images.githubusercontent.com/20141069/154014173-8ca7663c-6037-4052-ac6d-47e7b6d7d41a.png)

We need to update the  brace wrapping settings to *false*.
Otherwise reformatting with clang-format would lead to something like this:

![Screenshot_1](https://user-images.githubusercontent.com/20141069/154013895-989befa0-98e2-4683-b51b-6ec5b6bc2068.png)

If you want, i can do a PR for this.
